[package]
name = "pico-blinky"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = { version = "0.2.5", features = ["unproven"] }
rp-pico = "0.7"
panic-halt = "0.2"

# Optimize for size in release builds
[profile.release]
opt-level = "s"
